export const REGISTER_USER = 'USERS/REGISTER_USER'
export const USER_REGISTERED = 'USER/USER_REGISTERED'
export const REGISTRATION_FAILED = 'USER/REGISTRATION_FAILED'

export const SHOW_NOTIFICATION = 'NOTIFICATIONS/SHOW'
export const HIDE_NOTIFICATIONS = 'NOTIFICATIONS/HIDE'

export const CREATE_INVOICE = 'INVOICES/CREATE_INVOICE'
export const INVOICE_CREATED = 'INVOICES/INVOICE_CREATED'
export const CREATE_INVOICE_FAILED = 'INVOICES/CREATE_INVOICE_FAILED'

export const FETCH_USER_INVOICES = 'INVOICES/FETCH_USER_INVOICES'
export const USER_INVOICES_FETCHED = 'INVOICES/USER_INVOICES_FETCHED'
export const USER_INVOICES_FETCH_FAILED = 'INVOICES/USER_INVOICES_FETCH_FAILED'

export const USER_INVOICE_DELETE = 'INVOICES/USER_INVOICE_DELETE'
export const USER_INVOICE_GET = 'INVOICES/USER_INVOICE_GET'
export const USER_INVOICE_GET_SUCCESS = 'INVOICES/USER_INVOICE_GET_SUCCESS'
export const USER_INVOICE_EDIT = 'INVOICES/USER_INVOICE_EDIT'
export const USER_INVOICE_EDIT_SAVE = 'INVOICES/USER_INVOICE_EDIT_SAVE'

export const CREATE_INVOICE_DETAIL = 'INVOICES/CREATE_INVOICE_DETAIL'
export const INVOICE_DETAIL_CREATED = 'INVOICES/INVOICE_DETAIL_CREATED'
export const CREATE_INVOICE_DETAIL_FAILED = 'INVOICES/CREATE_INVOICE_DETAIL_FAILED'

export const FETCH_USER_INVOICE_DETAILS = 'INVOICES/FETCH_USER_INVOICE_DETAILS'
export const USER_INVOICE_DETAILS_FETCHED = 'INVOICES/USER_INVOICES_FETCHED'
export const USER_INVOICE_DETAILS_FETCH_FAILED = 'INVOICES/USER_INVOICES_FETCH_FAILED'

export const USER_INVOICE_DETAIL_DELETE = 'INVOICES/USER_INVOICE_DETAIL_DELETE'
export const USER_INVOICE_DETAIL_GET = 'INVOICES/USER_INVOICE_DETAIL_GET'
export const USER_INVOICE_DETAIL_GET_SUCCESS = 'INVOICES/USER_INVOICE_GET_DETAIL_SUCCESS'
export const USER_INVOICE_DETAIL_EDIT = 'INVOICES/USER_INVOICE_DETAIL_EDIT'
export const USER_INVOICE_DETAIL_EDIT_SAVE = 'INVOICES/USER_INVOICE_DETAIL_EDIT_SAVE'