export const REGISTER_USER = 'USERS/REGISTER_USER'
export const USER_REGISTERED = 'USER/USER_REGISTERED'
export const REGISTRATION_FAILED = 'USER/REGISTRATION_FAILED'

export const SHOW_NOTIFICATION = 'NOTIFICATIONS/SHOW'
export const HIDE_NOTIFICATIONS = 'NOTIFICATIONS/HIDE'

export const CREATE_INVOICE = 'INVOICES/CREATE_INVOICE'
export const INVOICE_CREATED = 'INVOICES/INVOICE_CREATED'
export const CREATE_INVOICE_FAILED = 'INVOICES/CREATE_INVOICE_FAILED'

export const FETCH_USER_INVOICES = 'INVOICES/FETCH_USER_INVOICES'
export const USER_INVOICES_FETCHED = 'INVOICES/USER_INVOICES_FETCHED'
export const USER_INVOICES_FETCH_FAILED = 'INVOICES/USER_INVOICES_FETCH_FAILED'
