export const REGISTER_USER = 'USERS/REGISTER_USER'
export const USER_REGISTERED = 'USER/USER_REGISTERED'
export const REGISTRATION_FAILED = 'USER/REGISTRATION_FAILED'

export const SHOW_NOTIFICATION = 'NOTIFICATIONS/SHOW'
export const HIDE_NOTIFICATIONS = 'NOTIFICATIONS/HIDE'

export const CREATE_INVOICE = 'INVOICES/CREATE_INVOICE'
